spring:

  datasource:
    url: jdbc:h2:mem:testedb
    driverClassName: org.h2.Driver
    username: developer
    password: developer

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


#keycloak Capital Global:
realm-capital-global:
  grant-type: 
  client_id: 
  client_secret: 
  endpoints:
    token: 
    insert-user: 